Nix

    # /mnt/etc/nixos/home-manager/home.nix
    { config, pkgs, inputs, ... }:
    {
      # Список пакетов, устанавливаемых для пользователя
      home.packages = with pkgs; [
        # Основные для Hyprland
        # hyprland # Обычно включается через programs.hyprland.enable в configuration.nix, но можно добавить и здесь
        waybar # Статус-бар
        hyprpaper # Для обоев
        rofi # Лаунчер приложений (rofi -show drun)
        kitty # Терминал
        brave # Браузер (может быть в overlays или Google Chrome / Chromium)
        dolphin # Файловый менеджер
        # whatsdesk # Проверьте наличие в Nixpkgs или overlay, иначе удалите
        # spotify # Проверьте наличие в Nixpkgs или overlay, иначе удалите
        cliphist # История буфера обмена
        clipman # Менеджер буфера обмена
        emacs # Emacs
        eww # Emacs Web Wowser (проверьте наличие)
        flameshot # Инструмент для скриншотов
        playerctl # Управление медиа
        pamixer # Управление звуком
        wpctl # Управление PipeWire
        brightnessctl # Управление яркостью
        yt-dlp # Скачивание видео/аудио
        xdg-desktop-portal-hyprland # Важно для интеграции с порталами XDG

        # Дополнительные шрифты (для rofi, waybar, терминала)
        noto-fonts
        noto-fonts-cjk
        noto-fonts-emoji
        fira-code # Пример, если используете Fira Code
        nerdfonts # Если нужны иконки в терминале/waybar (например, Hack Nerd Font)

        # Иконки и темы для GTK/Qt приложений
        papirus-icon-theme
        adwaita-qt # Для тем Qt-приложений
        adwaita-gtk3 # Для тем GTK-приложений
        libsForQt5.qt5ct # Утилита для настройки тем Qt
        lxappearance # Утилита для настройки тем GTK

        # Утилиты, которые могут понадобиться для некоторых скриптов
        xorg.xrdb # Для xrdb -load ~/.Xresources
        mpv # Медиаплеер
        sxiv # Просмотрщик изображений (для windowrulev2 = maximize, class:Sxiv)
        zathura # PDF-просмотрщик (для windowrulev2 = maximize, class:org.pwmt.zathura)
      ];
# Настройка Hyprland
      wayland.windowManager.hyprland = {
        enable = true;
        # Здесь мы вставляем содержимое вашего hyprland.conf
        extraConfig = ''
          # #######################################################################################
          # AUTOGENERATED HYPRLAND CONFIG.
          # PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hyprland.conf AND EDIT IT,
          # OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
          # #######################################################################################

          # autogenerated = 1 # remove this line to remove the warning

          # This is an example Hyprland config file.
          # Refer to the wiki for more information.
          # https://wiki.hyprland.org/Configuring/

          # Please note not all available settings / options are set here.
          # For a full list, see the wiki

          # You can split this configuration into multiple files
          # Create your files separately and then link them to this file like this:
          # source = ~/.config/hypr/myColors.conf


          ################
          ### MONITORS ###
          ################

          # See https://wiki.hyprland.org/Configuring/Monitors/
          monitor=DP-1,1920x1200@59.95000,0x0,1


          ###################
          ### MY PROGRAMS ###
          ###################

          # See https://wiki.hyprland.org/Configuring/Keywords/

          # Set programs that you use
          $terminal = kitty
          $browser = brave
          $fileManager = dolphin
          $menu = rofi -show drun -show-icons


          #################
          ### AUTOSTART ###
          #################

          # Autostart necessary processes (like notifications daemons, status bars, etc.)
          # Or execute your favorite apps at launch like this:

          # exec-once = $terminal
          # exec-once = nm-applet &
          exec-once = waybar & hyprpaper
          exec-once = [workspace 1 silent] $terminal
          exec-once = [workspace 3 silent] $browser
          exec-once = [workspace 4 silent] whatsdesk
          exec-once = [workspace 9 silent] spotify
          exec-once = wl-paste --type text --watch cliphist store
          exec-once = wl-paste --type image --watch cliphist store
          exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
          exec-once = xrdb -load ~/.Xresources
          exec-once = wl-paste --type text --watch clipman store --no-persist
          exec-once = wl-paste --type image --watch clipman store --no-persist
          exec-once = ${pkgs.writeShellScriptBin "start_emacs_wrapper" ''
            ${pkgs.emacs}/bin/emacsclient -c -a 'emacs'
          ''}/bin/start_emacs_wrapper
          exec-once = ${pkgs.writeShellScriptBin "eww_daemon_wrapper" ''
            ${pkgs.emacs}/bin/eww daemon
          ''}/bin/eww_daemon_wrapper


          #############################
          ### ENVIRONMENT VARIABLES ###
          #############################

          # See https://wiki.hyprland.org/Configuring/Environment-variables/

          env = XCURSOR_SIZE,24
          env = HYPRCURSOR_SIZE,24

          #####################
          ### LOOK AND FEEL ###
          #####################

          # Refer to https://wiki.hyprland.org/Configuring/Variables/

          # https://wiki.hyprland.org/Configuring/Variables/#general
          general {
              gaps_in = 5
              gaps_out = 15

              border_size = 3

              # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
              col.active_border = rgba(cc241dee) rgba(98971aee) 45deg
              col.inactive_border = rgba(595959aa)

              # Set to true enable resizing windows by clicking and dragging on borders and gaps
              resize_on_border = false

              # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
              allow_tearing = false
              layout = dwindle
          }

          # https://wiki.hyprland.org/Configuring/Variables/#decoration
          decoration {
              rounding = 10
              rounding_power = 10

              # Change transparency of focused and unfocused windows
              active_opacity = 1.0
              inactive_opacity = 1.0

              dim_inactive = false
              dim_strength = 0.3

              shadow {
                  enabled = false
                  range = 20
                  render_power = 4
                  color = rgba(1a1a1aee)
              }

              # https://wiki.hyprland.org/Configuring/Variables/#blur
              blur {
                  enabled = true
                  size = 3
                  passes = 3

                  vibrancy = 0.0
              }
          }

          # https://wiki.hyprland.org/Configuring/Variables/#animations
          animations {
              enabled = yes, please :)

              # Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

              bezier = easeOutQuint,0.23,1,0.32,1
              bezier = easeInOutCubic,0.65,0.05,0.36,1
              bezier = linear,0,0,1,1
              bezier = almostLinear,0.5,0.5,0.75,1.0
              bezier = quick,0.15,0,0.1,1

              animation = global, 1, 2, default
              animation = windows, 1, 1.79, easeOutQuint
              animation = windowsIn, 1, 1.1, easeOutQuint, popin 87%
              animation = windowsOut, 1, 1.49, linear, popin 87%
              animation = fadeIn, 1, 1.73, almostLinear
              animation = fadeOut, 1, 1.46, almostLinear
              animation = fade, 1, 1.03, quick
              animation = layers, 1, 1.81, easeOutQuint
              animation = layersIn, 1, 2, easeOutQuint, fade
              animation = layersOut, 1, 1.5, linear, fade
              animation = fadeLayersIn, 1, 1.79, almostLinear
              animation = fadeLayersOut, 1, 1.39, almostLinear
              animation = workspaces, 1, 2.5, default, slide, fade
              animation = workspacesIn, 1, 2.5, default, slide, fade
              animation = workspacesOut, 1, 2.5, default, slide, fade
          }

          # Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
          # "Smart gaps" / "No gaps when only"
          # uncomment all if you wish to use that.
          # workspace = w[tv1], gapsout:0, gapsin:0
          # workspace = f[1], gapsout:0, gapsin:0
          # windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
          # windowrule = rounding 0, floating:0, onworkspace:w[tv1]
          # windowrule = bordersize 0, floating:0, onworkspace:f[1]
          # windowrule = rounding 0, floating:0, onworkspace:f[1]

          # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
          dwindle {
              pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
              preserve_split = true # You probably want this
          }

          # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
          master {
              new_status = master
          }

          # https://wiki.hyprland.org/Configuring/Variables/#misc
          misc {
              force_default_wallpaper = 1 # Set to 0 or 1 to disable the anime mascot wallpapers
              disable_hyprland_logo = false # If true disables the random hyprland logo / anime background. :(
          }


          #############
          ### INPUT ###
          #############

          # https://wiki.hyprland.org/Configuring/Variables/#input
          input {
              kb_layout = us, ara
              kb_options = grp:win_space_toggle,ctrl:swapcaps, altwin:swap_ralt_rwin
              mouse_refocus = false
              follow_mouse = 1

              repeat_delay = 250
              repeat_rate = 30

              sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

              touchpad {
                  natural_scroll = false
              }
          }
# https://wiki.hyprland.org/Configuring/Variables/#gestures
          gestures {
              workspace_swipe = false
          }

          # Example per-device config
          # See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
          device {
              name = epic-mouse-v1
              sensitivity = -0.5
          }


          ###################
          ### KEYBINDINGS ###
          ###################

          # See https://wiki.hyprland.org/Configuring/Keywords/
          $mainMod = SUPER # Sets "Windows" key as main modifier

          # Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
          bind = $mainMod, Return, exec, $terminal
          bind = $mainMod, Q, killactive,
          bind = $mainMod SHIFT, q, exit,
          unbind = SUPER, M
          bind = $mainMod, E, exec, $fileManager
          bind = $mainMod, V, exec, hyprctl --batch "dispatch togglefloating ; dispatch centerwindow 1"
          bind = $mainMod, P, exec, $menu
          bind = $mainMod SHIFT, P, exec, mpv $(wl-paste)
          bind = $mainMod SHIFT, D, exec, yt-dlp $(wl-paste)
          # bind = $mainMod, P, pseudo, # dwindle
          bind = $mainMod, I, togglesplit, # dwindle
          bind = SUPER SHIFT, C, exec, cliphist list | wofi --dmenu | cliphist decode | wl-copy
          bind = SUPER, W, exec, pkill -9 waybar && waybar &


          # Move focus with mainMod + arrow keys
          bind = $mainMod, H, movefocus, l
          bind = $mainMod, L, movefocus, r
          bind = $mainMod, K, movefocus, u
          bind = $mainMod, J, movefocus, d

          # Switch workspaces with mainMod + [0-9]
          bind = $mainMod, 1, workspace, 1
          bind = $mainMod, 2, workspace, 2
          bind = $mainMod, 3, workspace, 3
          bind = $mainMod, 4, workspace, 4
          bind = $mainMod, 5, workspace, 5
          bind = $mainMod, 6, workspace, 6
          bind = $mainMod, 7, workspace, 7
          bind = $mainMod, 8, workspace, 8
          bind = $mainMod, 9, workspace, 9
          bind = $mainMod, 0, workspace, 10

          # Move active window to a workspace with mainMod + SHIFT + [0-9]
          bind = $mainMod SHIFT, 1, movetoworkspace, 1
          bind = $mainMod SHIFT, 2, movetoworkspace, 2
          bind = $mainMod SHIFT, 3, movetoworkspace, 3
          bind = $mainMod SHIFT, 4, movetoworkspace, 4
          bind = $mainMod SHIFT, 5, movetoworkspace, 5
          bind = $mainMod SHIFT, 6, movetoworkspace, 6
          bind = $mainMod SHIFT, 7, movetoworkspace, 7
          bind = $mainMod SHIFT, 8, movetoworkspace, 8
          bind = $mainMod SHIFT, 9, movetoworkspace, 9
          bind = $mainMod SHIFT, 0, movetoworkspace, 10
          bind = SUPER, Tab, workspace, previous

          # Example special workspace (scratchpad)
          bind = $mainMod, semicolon, togglespecialworkspace, magic
          bind = $mainMod SHIFT, semicolon, movetoworkspace, special:magic

          # Scroll through existing workspaces with mainMod + scroll
          bind = $mainMod, mouse_down, workspace, e+1
          bind = $mainMod, mouse_up, workspace, e-1

          # Move/resize windows with mainMod + LMB/RMB and dragging
          bindm = $mainMod, mouse:272, movewindow
          bindm = $mainMod, mouse:273, resizewindow

          # Screenshot
          bind = , Print, exec, flameshot gui
          bind = $mainMod, Print, exec, flameshot gui --raw | wl-copy

          # Pause/Play music
          bind = , pause, exec, playerctl --player=spotify play-pause

          # Fullscreen
          bind = SUPER, F, fullscreen, 1
          bind = SUPER SHIFT, F, fullscreen
          bind = ALT, TAB, cyclenext

          # Master
          bind = SUPER, M, layoutmsg, master
          # Скрипты, которые были в ~/.local/bin/
      # Мы создаем их декларативно через Home Manager
      # Эти скрипты будут автоматически добавлены в PATH пользователя
      # и их не нужно будет вызывать по полному пути.
      # Но в hyprland.conf лучше использовать ${pkgs.имя_скрипта}/bin/имя_скрипта

      # Скрипт start_emacs.sh
      home.activation.linkEmacsScript = pkgs.lib.mkIf true { # Просто для примера, можно использовать home.file
        after = [ "writeBoundary" ];
        before = [ "installPackages" ];
        # Мы создаем обертку для Emacs через Nix, чтобы гарантировать, что она находится в PATH и работает
        # exec-once = ${pkgs.writeShellScriptBin "start_emacs_wrapper" ''
        #   ${pkgs.emacs}/bin/emacsclient -c -a 'emacs'
        # ''}/bin/start_emacs_wrapper
        # Мы это уже встроили прямо в extraConfig, так что тут не нужно.
      };

      # Скрипт record
      home.activation.linkRecordScript = pkgs.lib.mkIf true {
        after = [ "writeBoundary" ];
        before = [ "installPackages" ];
        # bind = SUPER, F12, exec, ${pkgs.writeShellScriptBin "record_wrapper" ''
        #   # Здесь может быть содержимое вашего скрипта record
        #   # Например, если он делает что-то простое:
        #   # grim -g "$(slurp)" -o $(date +%Y%m%d_%H%M%S).png && notify-send "Screenshot taken!"
        # ''}/bin/record_wrapper
        # Мы это тоже уже встроили прямо в extraConfig.
      };


      home.stateVersion = "24.05"; # <--- ВАЖНО: Ваша версия Home Manager, должна совпадать с system.stateVersion
    }
